apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-valkey-storage-external
  labels:
    app: backend-valkey-external
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem