apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: 3scale
spec:
  wildcardDomain: apps.ocp.kxllw.sandbox742.opentlc.com
  resourceRequirementsEnabled: false
  externalComponents:
    backend:
      redis: true
    system:
      database: true
      redis: true
    zync:
      database: false
  system:
    fileStorage:
      persistentVolumeClaim:
        storageClassName: gp3-csi
    database:
      postgresql: {}