apiVersion: v1
kind: Service
metadata:
  name: system-valkey-service
  labels:
    app: system-valkey-external
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    deployment: system-valkey-external