apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: 3scale-postgresql
    app.openshift.io/runtime: postgresql
    app.kubernetes.io/component: 3scale-postgresql
    app.kubernetes.io/instance: 3scale-postgresql
    app.kubernetes.io/part-of: 3scale
    backstage.io/kubernetes-id: 3scale
  name: postgresql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem

